# Generated by Django 4.2.5 on 2023-11-16 10:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(help_text='Enter phone number in the format +2348012345678', max_length=15, unique=True, verbose_name='Phone Number')),
                ('rc_number', models.CharField(help_text='Enter RC Number in the format BN12345', max_length=20, unique=True, verbose_name='RC Number')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=20, unique=True, verbose_name='ID Number')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Code')),
                ('location', models.CharField(max_length=255)),
                ('date_awarded', models.DateField(blank=True, default=True, null=True, verbose_name='Date Awarded')),
                ('date_contract_reviewed', models.DateField(blank=True, null=True, verbose_name='Date Contract Reviewed')),
                ('contract_sum', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Contract Sum (in Naira)')),
                ('revised_contract_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Revised Contract Sum')),
                ('completion_status', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Completion Status (%)')),
                ('project_completed', models.CharField(choices=[('', 'Select Option'), ('1', 'Yes'), ('2', 'No')], max_length=4)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patdalyapp.contractor', verbose_name='Contractor')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patdalyapp.supervisor', verbose_name='Supervised by')),
            ],
        ),
    ]
